const byte A =10; // PIN FOR TOGGLING AS INPUT AND OUTPUT
void setup() 
{
  // TIMER 1 TO GENERATE CARRIER WAVES //


TCCR1A = 0;// SET TIMER AND COUNTER CONTROL REGISTER A TO ZERO
TCCR1B = 0;// SET TIMER AND COUNTER CONTROL REGISTER B TO ZERO
OCR1A = 7; //(16÷(OCR1A+1)÷2)×1000 = FREQ IN KHz => (OCR1A=8-1)
TCCR1A =(1<<COM1B0); //TO TOGGLE OC1A ON COMPARE MATCH
TCCR1B =(1<<WGM12); // SETTING T0 CTC MODE  
TCCR1B|=(1<<CS10);  //16MHZ/1 (NO PRESCALER)
}

void loop()
{
  
  // TIMER 0 TO MODULATE SIGNAL // (SINCE TIMER 0 IS A FUNCTION OF DELAY())
  
pinMode(A,OUTPUT);
delay(100); // UTILISING TIMER 0 FOR MODULATING HIGH
pinMode(A,INPUT);
delay(100); //UTILISING TIMER 0 FOR MODULATING LOW 
}
